### ISSUE TITLE
Malformed Input Exception for Hot List

### ISSUE THREAD

**Issue by Epure-Tofanel-Carlo** [Bram--/bggclient#31]
When calling for hotlist, the request completes, comes back with size of 0, error is most likely from the response class.
The error appeared when the game [Tír na nÓg](https://boardgamegeek.com/boardgame/343433/tir-na-nog) appeared in  "The Hotness", one character in that name is causing the error I think, as everything worked fine until it entered the list at ˜49th place. Though when getting it's boardgame details with a simple get etc., it works and prints just fine.
The error persists after tyr na nog exited the top as well

```
 internal companion object {
        /** Create a new response from the given response string, using the [mapper]. */
        suspend inline fun <reified T> from(bodyAsText: String, mapper: ObjectMapper): Response<T> =
            withContext(Dispatchers.Default) {
                try {
                    Response(data = mapper.readValue(bodyAsText, T::class.java))
                } catch (e: JacksonException) {
                    Logger.i("Error parsing response", e)
                    Response(error = bodyAsText)
                }
            }
    }
```
   Response(data = mapper.readValue(bodyAsText, T::class.java)) , due to this I get the following error after making the logging verbose
   
   ```
   2024-09-12 11:45:37.871 14552-14552 HotListApi              com.personal.boardgamebazaar           E  Error in getHotList
                                                                                                    io.ktor.utils.io.charsets.MalformedInputException: Input length = 1
                                                                                                    	at io.ktor.utils.io.charsets.CharsetJVMKt.throwExceptionWrapped(CharsetJVM.kt:370)
                                                                                                    	at io.ktor.utils.io.charsets.CharsetJVMKt.decode(CharsetJVM.kt:241)
                                                                                                    	at io.ktor.utils.io.charsets.EncodingKt.decode(Encoding.kt:103)
                                                                                                    	at io.ktor.utils.io.charsets.EncodingKt.decode$default(Encoding.kt:101)
                                                                                                    	at io.ktor.client.statement.HttpResponseKt.bodyAsText(HttpResponse.kt:89)
                                                                                                    	at io.ktor.client.statement.HttpResponseKt.bodyAsText$default(HttpResponse.kt:84)
                                                                                                    	at org.audux.bgg.request.HotListKt$hotList$1.invokeSuspend(HotList.kt:36)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
                                                                                                    	at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
                                                                                                    	at kotlinx.coroutines.internal.DispatchedContinuation.resumeWith(DispatchedContinuation.kt:341)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.kt:135)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.kt:109)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.kt:11)
                                                                                                    	at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.kt:59)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:313)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8762)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
                                                                                         
 ```                                                                                                   	
I suggest maybe making the charset explicit, or handling the MalformedInputException in particular.
If you need more details I can always provide, I'm currently developing an Android app using the bggclient

**Comment by Bram--** [comment]
Thanks, will look into that this week!

**Comment by Bram--** [comment]
It seems the BGG API unexpectedly returns a gzipped encoded response specifically for the /hot?type=boardgame endpoint. This wasn't something I anticipated, as it doesn't happen on other endpoints. The presence of certain characters in game titles, like those in "Tír na nÓg," work perfectly fine using the UTF-8 charset.

I've written a test for and added support for handling gzipped responses in the Client. This should resolve the MalformedInputExceptions you're seeing.

Please give it a try with [the updated Client](https://central.sonatype.com/artifact/org.audux.bgg/bggclient/0.9.2) and let me know if you encounter any further problems.

Thanks again for bringing this to my attention!
