### ISSUE TITLE
Unrecognized Property Exception

### ISSUE THREAD

**Issue by Epure-Tofanel-Carlo** [Bram--/bggclient#33]
The xml now contains a ''poll-summary" field, which leads to failed desereialization for every Thing object, i would just mark it as ignorable with @JsonIgnoreProperties("poll-summary") if the stats call still returns what is needed
```
  I  Error parsing response
                                                                                                    com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "poll-summary" (class org.audux.bgg.response.Thing), not marked as ignorable (27 known properties: "datePublished", "names", "name", "maxPlayers", "yearPublished", "minplaytime", "polls", "videos", "issueIndex", "id", "minPlayers", "statistics", "seriesCode", "maxplaytime", "thumbnail", "minAge", "comments", "releaseDate", "links", "type", "playingtime", "description", "poll", "image", "marketplacelistings", "versions", "link"])
                                                                                                     at [Source: (StringReader); line: 247, column: 8] (through reference chain: org.audux.bgg.response.Things["item"]->java.util.ArrayList[0]->org.audux.bgg.response.Thing["poll-summary"])
                                                                                                    	at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1153)
                                                                                                    	at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:2241)
                                                                                                    	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1793)
                                                                                                    	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperties(BeanDeserializerBase.java:1743)
                                                                                                    	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:546)
                                                                                                    	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1493)
                                                                                                    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:348)
                                                                                                    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
                                                                                                    	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:122)
                                                                                                    	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:361)
                                                                                                    	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:246)
                                                                                                    	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:30)
                                                                                                    	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:545)
                                                                                                    	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeWithErrorWrapping(BeanDeserializer.java:570)
                                                                                                    	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:440)
                                                                                                    	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1493)
                                                                                                    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:348)
                                                                                                    	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
                                                                                                    	at com.fasterxml.jackson.dataformat.xml.deser.WrapperHandlingDeserializer.deserialize(WrapperHandlingDeserializer.java:122)
                                                                                                    	at com.fasterxml.jackson.dataformat.xml.deser.XmlDeserializationContext.readRootValue(XmlDeserializationContext.java:104)
                                                                                                    	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4905)
                                                                                                    	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3848)
                                                                                                    	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3816)
                                                                                                    	at org.audux.bgg.request.ThingsKt$things$1$invokeSuspend$lambda$4$$inlined$from$1.invokeSuspend(Response.kt:46)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:102)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:816)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707) 
```

**Comment by Bram--** [comment]
Thanks (again) for the report! I've just added the (new) property to the Things Response object. I've also included a new configuration property so that you can ignore errors on new fields like this in the future.

I'm just publishing [0.9.4](https://github.com/Bram--/bggclient/releases/tag/0.9.4) with the following changes:

 * Add JVMtoolchain(11) version to build file
 * Add nullable error field to item as sometimes the API can return an item with only an error field set when retrieving things in bulk
 * Add the new field poll-summary.
 * Adds BggClientConfiguration#failOnUnknownProperties to configure the client to parse regardless of what the API returns. This is especially useful to make sure fields added to the XML API by BGG do not crash the client.

**Comment by Epure-Tofanel-Carlo** [comment]
Thank you so much!! 🥹
